### ISSUE TITLE
Any chance of a parts list? 

### ISSUE THREAD

**Issue by f0rk3d** [ShoolerM/HackMyHat2#1]
I spotted you at the con, but wasn't able to chat.  If say, I wanted to build my own hackable wearable,  what parts did you use?   I'm new to the hardware side of things, so would love to learn. Any recommendations would be appreciated

**Comment by ShoolerM** [comment]
Hey sure thing. I just used a raspberry pi zero w and its GPIO, WS2812B led strips, and a small usb speaker.
Let me know if you have any questions/want any guidance when making your project (:

**Comment by f0rk3d** [comment]
I was looking through the code and guessing it was something like that.  I've got a rpi zero laying around here somewhere just begging for something to do.   Thanks!
